import Link from "next/link";
import { auth } from "@/server/auth";

export default async function Home() {
  const session = await auth();

  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col items-center justify-center gap-8 p-8 text-center">
      <div className="space-y-3">
        <h1 className="text-4xl font-bold tracking-tight">Welcome 👋</h1>
        <p className="text-gray-600">
          This app was generated by Stackr with a working authentication portal.
        </p>
      </div>

      {session?.user ? (
        <div className="flex flex-col items-center gap-3">
          <p className="text-sm text-gray-500">
            Signed in as <span className="font-medium text-gray-900">{session.user.email}</span>
          </p>
          <Link
            href="/account"
            className="rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700"
          >
            Go to account
          </Link>
        </div>
      ) : (
        <div className="flex gap-3">
          <Link
            href="/login"
            className="rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700"
          >
            Sign in
          </Link>
          <Link
            href="/register"
            className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-100"
          >
            Create account
          </Link>
        </div>
      )}
    </main>
  );
}
